# Generated by Django 5.1.5 on 2025-01-31 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'verbose_name': 'Блюда', 'verbose_name_plural': 'Блюда'},
        ),
    ]
